name: marcadores_mundial_app
description: "FIFA World Cup 2026 - Live Scores, Standings & Teams"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  video_player: ^2.9.2
  chewie: ^1.8.4
  sembast: ^3.8.0
  sembast_web: ^2.2.0
  path_provider: ^2.1.0
  path: ^1.9.0
  intl: ^0.19.0
  share_plus: ^10.1.4
  flutter_local_notifications: ^18.0.1
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  supabase: ^2.13.0
  image_picker: ^1.1.2
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "asset/img/marcador_logo_ap.png"

flutter:
  uses-material-design: true
